// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7f5Edm-_ntkeXbprCnraQyXHZJK4WTPM',
    appId: '1:708272940168:web:b90914eefa1145fbbbab3d',
    messagingSenderId: '708272940168',
    projectId: 'newcommunity2-f47b4',
    authDomain: 'newcommunity2-f47b4.firebaseapp.com',
    storageBucket: 'newcommunity2-f47b4.firebasestorage.app',
    measurementId: 'G-WE2346M4NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcruDYDNpFUAw8xRMY89qAVm4n8Ax7Aq0',
    appId: '1:708272940168:android:31f442d1efcf352bbbab3d',
    messagingSenderId: '708272940168',
    projectId: 'newcommunity2-f47b4',
    storageBucket: 'newcommunity2-f47b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHHha1cq_i2Ne0ungBk3ypCqt2FvmXDTQ',
    appId: '1:708272940168:ios:ff6b631c94555800bbab3d',
    messagingSenderId: '708272940168',
    projectId: 'newcommunity2-f47b4',
    storageBucket: 'newcommunity2-f47b4.firebasestorage.app',
    iosBundleId: 'com.example.newCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHHha1cq_i2Ne0ungBk3ypCqt2FvmXDTQ',
    appId: '1:708272940168:ios:ff6b631c94555800bbab3d',
    messagingSenderId: '708272940168',
    projectId: 'newcommunity2-f47b4',
    storageBucket: 'newcommunity2-f47b4.firebasestorage.app',
    iosBundleId: 'com.example.newCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7f5Edm-_ntkeXbprCnraQyXHZJK4WTPM',
    appId: '1:708272940168:web:877e2843ecad3331bbab3d',
    messagingSenderId: '708272940168',
    projectId: 'newcommunity2-f47b4',
    authDomain: 'newcommunity2-f47b4.firebaseapp.com',
    storageBucket: 'newcommunity2-f47b4.firebasestorage.app',
    measurementId: 'G-F1K3F46WML',
  );
}
